# Generated by Django 4.0.1 on 2022-01-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proverb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proverb', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
            ],
        ),
    ]
