# Generated by Django 4.0.1 on 2022-01-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proverbsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proverb',
            name='meaning',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proverb',
            name='proverb',
            field=models.TextField(),
        ),
    ]
