# Generated by Django 4.0.1 on 2022-01-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('definition', models.CharField(max_length=80)),
            ],
        ),
    ]
